- hosts: kubeworker
  name: "Playbook"
  remote_user: kubeworker

  tasks:
    - name: Update
      ansible.builtin.apt:
          name: "*"
          state: latest

    - name: Install Required Packages
      ansible.builtin.apt:
        pkg:
        - systemd-resolved
        
    - name: Check directories
      stat:
        path: '{{ k3s_path }}'
      register: directory_data

    - debug: var=directory_data.stat.exists

    - name: Create K3S directory if it doesn't already exist
      file:
        path: '{{ k3s_path }}'
        state: directory
      when: not directory_data.stat.exists

    - name: Render Template Registry
      ansible.builtin.template:
        src: configs/registries.j2
        dest: '{{ k3s_path }}/registries.yaml'

    - name: Replace DNS
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#DNS='
        line: 'DNS={{ dns }}'
    
    - name: Replace Fallback DNS
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#FallbackDNS='
        line: 'FallbackDNS={{ fallback_dns }}'
        

    - name: Render Template Registry
      ansible.builtin.template:
        src: configs/registries.j2
        dest: '{{ k3s_path }}/registries.yaml'

    - name: Restart service Systemd Resolved Service
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: systemd-resolved

    - name: Install K3S
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | sh -s -
        chdir: ~
      environment:
        K3S_URL: 'https://192.168.46.146:6443'
        K3S_TOKEN: '{{ k3s_token }}'